version: "3"

x-logging: &default-logging
   driver: "k8s-file"

services:
  loki:
    image: phx.ocir.io/idvjmdrn1r3d/observstack/grafana/loki:2.2.1
    ports:
      - "3100:3100"
    command: 
      - -config.file=/etc/loki/local-config.yaml
      - -table-manager.retention-period=1d
      - -table-manager.retention-deletes-enabled=true
    labels:
      namespace: monitoring
    healthcheck:
      test: sleep 90
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 120s
    logging: *default-logging

  grafana:
    image: phx.ocir.io/idvjmdrn1r3d/observstack/grafana/grafana:8.0.6
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboards:/etc/grafana/dashboards
      # This volume is used as persistent storage (database and plugins)
      - ./data:/var/lib/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    labels:
      namespace: monitoring
    user: "root"
    logging: *default-logging

  jaeger:
    image: phx.ocir.io/idvjmdrn1r3d/observstack/jaegertracing/all-in-one:1.24.0
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "9411:9411"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "16686:16686"
    labels:
      namespace: monitoring
    logging: *default-logging

  prometheus:
    image: phx.ocir.io/idvjmdrn1r3d/observstack/prom/prometheus:v2.28.1
    user: root
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=1d
      - --enable-feature=exemplar-storage
      - --log.level=debug
      - --web.enable-admin-api
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    labels:
      namespace: monitoring
    logging: *default-logging

  hotrod:
    image: phx.ocir.io/idvjmdrn1r3d/observstack/jaegertracing/example-hotrod:1.35.0
    ports:
      - "8080-8083:8080-8083"
    environment:
      JAEGER_ENDPOINT: 'http://jaeger:14268/api/traces'
      JAEGER_TAGS: job=demo/hotrod
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    labels:
      namespace: demo
    logging: *default-logging

  vector:
    image: phx.ocir.io/idvjmdrn1r3d/observstack/timberio/vector:0.22.1-alpine
    ports:
      - "8383:8383"
    environment:
      DOCKER_HOST: 'unix:///run/user/501/podman/podman.sock'
    volumes:
      - /run/user/501/podman/podman.sock:/run/user/501/podman/podman.sock
      - ./vector.toml:/etc/vector/vector.toml:ro 
    user: root
    labels:
      namespace: monitoring
      service: vector
    depends_on:
      loki:
        condition: service_healthy
