version: "3"

x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    labels: namespace
    loki-relabel-config: |
      - action: replace
        source_labels: ["namespace","compose_service"]
        separator: "/"
        target_label: job
      - action: replace
        source_labels: ["container_id"]
        target_label: hostname

services:
  loki:
    image: grafana/loki:2.2.1
    ports:
      - "3100:3100"
    command: 
      - -config.file=/etc/loki/local-config.yaml
      - -table-manager.retention-period=1d
      - -table-manager.retention-deletes-enabled=true
    labels:
      namespace: monitoring
    logging: *default-logging

  grafana:
    image: grafana/grafana:8.0.6
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboards:/etc/grafana/dashboards
    ports:
      - "3000:3000"
    labels:
      namespace: monitoring
    logging: *default-logging

  jaeger:
    image: jaegertracing/all-in-one:1.24.0
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "9411:9411"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "16686:16686"
    labels:
      namespace: monitoring
    logging: *default-logging

  prometheus:
    image: prom/prometheus:v2.28.1
    user: root
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=1d
      - --enable-feature=exemplar-storage
      - --log.level=debug
      - --web.enable-admin-api
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    labels:
      namespace: monitoring
    logging: *default-logging

  hotrod:
    image: us-ashburn-1.ocir.io/idh4mthlx4v6/observarch/hotrod:1.0.5
    ports:
      - "8080-8083:8080-8083"
    environment:
      JAEGER_ENDPOINT: 'http://jaeger:14268/api/traces'
      JAEGER_TAGS: job=demo/hotrod
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    labels:
      namespace: demo
    logging: *default-logging

