apiVersion: v1
data:
  overrides.yaml: |
    overrides:
  tempo.yaml: |
    compactor:
        compaction:
            block_retention: 24h
    distributor:
        log_received_traces: true
        receivers:
            otlp:
                protocols:
                    grpc: null
    ingester: {}
    memberlist:
        abort_if_cluster_join_fails: false
        bind_port: 7946
        join_members:
            - tempo-members:7946
    querier:
        frontend_worker:
            frontend_address: tempo:9095
    #search_enabled: true
    server:
        http_listen_port: 3200
    storage:
        trace:
            backend: local
            local:
                path: /tmp/tempo/traces
            wal:
                path: /var/tempo/wal
kind: ConfigMap
metadata:
  name: tempo
  namespace: monitoring
