apiVersion: v1
kind: Service
metadata:
  labels:
    name: tempo
  name: tempo
  namespace: monitoring
spec:
  ports:
  - name: tempo-prom-metrics
    port: 3200
    targetPort: 3200
  - name: tempo-memberlist
    port: 9095
    targetPort: 9095
  - name: tempo-otlp
    port: 4317
    targetPort: 4317
  - name: tempo-query-jaeger-ui
    port: 16686
    targetPort: 16686
  - name: tempo-query-jaeger-metrics
    port: 16687
    targetPort: 16687
  selector:
    app: tempo-members
    name: tempo
