apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: tempo-members
    name: tempo
  name: tempo
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tempo
  serviceName: tempo
  template:
    metadata:
      annotations:
        config_hash: 42ae8c66401a25a52fb8788c1e33ed1d
      labels:
        app: tempo-members
        name: tempo
    spec:
      containers:
      - args:
        - -target=scalable-single-binary
        - -config.file=/conf/tempo.yaml
        - -mem-ballast-size-mbs=1024
        image: phx.ocir.io/idvjmdrn1r3d/observstack/grafana/tempo:main-6801c1b
        imagePullPolicy: IfNotPresent
        name: tempo
        ports:
        - containerPort: 3200
          name: prom-metrics
        - containerPort: 9095
          name: memberlist
        - containerPort: 4317
          name: otlp
        resources:
          limits:
            cpu: 150m
            memory: 850Mi
          requests:
            cpu: 100m
            memory: 700Mi
        volumeMounts:
        - mountPath: /conf
          name: tempo-conf
        - mountPath: /var/tempo
          name: tempo-data
      - args:
        - --query.base-path=/
        - --grpc-storage-plugin.configuration-file=/conf/tempo-query.yaml
        image: phx.ocir.io/idvjmdrn1r3d/observstack/grafana/tempo-query:main-6801c1b
        imagePullPolicy: IfNotPresent
        name: tempo-query
        ports:
        - containerPort: 16686
          name: jaeger-ui
        - containerPort: 16687
          name: jaeger-metrics
        volumeMounts:
        - mountPath: /conf
          name: tempo-query-conf
      volumes:
      - configMap:
          name: tempo-query
        name: tempo-query-conf
      - configMap:
          name: tempo
        name: tempo-conf
      - name: tempo-data
        persistentVolumeClaim:
          claimName: tempo-data
  updateStrategy:
    type: RollingUpdate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   labels:
     app: tempo
   name: tempo-data
   namespace: monitoring
spec:
   accessModes:
   - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
