apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: monitoring
data:
  agent.yaml: |
    receivers:
      otlp/http:
        protocols: 
          http:
      otlp/grpc:
        protocols: 
          grpc:
      jaeger:
        protocols:
          thrift_http:
            endpoint: 0.0.0.0:14268
      jaeger/grpc:
        protocols:
          grpc:
    processors:
      metricstransform:
         transforms:
            include: http_status_200_rolldice_delta
            action: update
            operations:
            - action: add_label
              new_label: version
              new_value: 1.1
           
      k8sattributes/2:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
          labels:
            - tag_name: app
              key: app
              from: pod
        pod_association:
          - sources:
            - from: resource_attribute
              name: k8s.pod.ip
          - sources:
            - from: connection
              name: ip
          - sources:
            - from: resource_attribute
              name: ip 

      resource:
        attributes:
        - key: "pod_name"
          from_attribute: host.name
          action: insert

    exporters:
      logging:
        loglevel: info
      otlp:
        endpoint: "otelcollector:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces/jaeger:
          receivers: [jaeger]
          processors: [k8sattributes/2, resource]
          exporters: [otlp, logging]
        traces/jaeger_grpc:
          receivers: [jaeger/grpc]
          processors: [k8sattributes/2, resource]
          exporters: [otlp, logging]
        traces/otel:
          receivers: [otlp/grpc]
          processors: [k8sattributes/2]
          exporters: [otlp]
        logs/otel:
          receivers: [otlp/grpc]
          processors: [k8sattributes/2]
          exporters: [otlp]
        metrics/otel:
          receivers: [otlp/grpc]
          processors: [k8sattributes/2, metricstransform]
          exporters: [otlp]
