{
 "title": "Demo - Hotrod",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(hotrod_customer_request_latency_count{job=~\"demo/hotrod\"}[1m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(hotrod_customer_request_latency_bucket{job=~\"demo/hotrod\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(hotrod_customer_request_latency_bucket{job=~\"demo/hotrod\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(hotrod_customer_request_latency_sum{job=~\"demo/hotrod\"}[$__rate_interval])) * 1 / sum(rate(hotrod_customer_request_latency_count{job=~\"demo/hotrod\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"demo/hotrod\"}"
    }
   ]
  }
 ]
}