apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: observe-app
  labels:
    app: observe-app
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: None
    #Either put these here or in pod config
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"

spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: observe-app

