apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: monitoring
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
          http:
    processors:

    exporters:
      logging:
      otlp:
        endpoint: "tempo:4317"
        tls:
          insecure: true
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
        headers:
          X-Scope-OrgID: fake
        format: "json"
        tls:
          insecure: true
        labels:
          resource: 
            k8s.pod.name: "k8s_pod_name"
            k8s.pod.uid: "k8s_pod_uid"
            k8s.namespace.name: "k8s_namespace_name"
            service.name: "service_name"
          record:
            severity: "severity"
      prometheusremotewrite:
        endpoint: "http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
        tls:
          insecure: true
        resource_to_telemetry_conversion:
          enabled: true
        external_labels:
          author: rafan
      prometheus:
        endpoint: "prometheus.monitoring.svc.cluster.local:9090"
        namespace: test-space
        const_labels:
           label1: value1
        send_timestamps: true
        metric_expiration: 180m
        resource_to_telemetry_conversion:
          enabled: true


    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging, otlp]
        logs:
          receivers: [otlp]
          exporters: [logging, loki]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [logging, prometheusremotewrite]