apiVersion: v1
kind: Service
metadata:
  name: otelcollector
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: None
spec:
  ports:
    - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver.
      port: 4317
      protocol: TCP
      targetPort: 4317
  selector:
    app: otelcollector
  type: ClusterIP