apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
     grafana_datasource: "1"
  namespace: monitoring
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - uid: KOEtPV3nk
        name: Prometheus
        type: prometheus
        typeName: Prometheus
        typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
        access: proxy
        url: http://prometheus:9090
        password: ''
        user: ''
        database: ''
        basicAuth: false
        isDefault: false
        jsonData:
          httpMethod: POST
          exemplarTraceIdDestinations:
            - datasourceUid: 7AcKm9qnk
              name: trace_id
        readOnly: false
      - uid: o-HQj6M4k
        name: Loki
        type: loki
        typeName: Loki
        typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
        access: proxy
        url: http://loki:3100
        password: ''
        user: ''
        database: ''
        basicAuth: false
        isDefault: false
        jsonData:
          derivedFields:
          - datasourceUid: 7AcKm9qnk
            matcherRegex: '["]?[tT][rR][aA][cC][eE][\s\S]?[\-]?[\_]?[iI][dD]["]?[=|:]["]?(\w+)["]?'
            name: jaeger
            url: "$${__value.raw}"
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: "tenant1"
        readOnly: false
      - uid: 7AcKm9qnk
        name: Tempo
        type: tempo
        typeName: Tempo
        typeLogoUrl: public/app/plugins/datasource/tempo/img/tempo_logo.svg
        access: proxy
        url: http://tempo:3200
        password: ''
        user: ''
        database: ''
        basicAuth: false
        isDefault: false
        jsonData:
          tracesToLogs:
            datasourceUid: o-HQj6M4k
            lokiSearch: true
            mapTagNamesEnabled: true
            mappedTags:
            - key: pod_name
              value: pod_name
            tags: []
        readOnly: false